//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZSRF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Services = new HashSet<Service>();
        }
    
        public int clientID { get; set; }
        public string CLastName { get; set; }
        public string CFirstName { get; set; }
        public string CAddress { get; set; }
        public string CCity { get; set; }
        public string CState { get; set; }
        public string CZip { get; set; }
        public string CCountry { get; set; }
        public string CPhone { get; set; }
        public string CAge { get; set; }
        public Nullable<System.DateTime> CDOB { get; set; }
        public string CEmail { get; set; }
        public string CCellPhone { get; set; }
        public string CDiagnosis { get; set; }
        public string CReferLast { get; set; }
        public string CReferFirst { get; set; }
        public string CReferRelation { get; set; }
        public string CReferAddress { get; set; }
        public string CReferCity { get; set; }
        public string CReferState { get; set; }
        public string CReferZip { get; set; }
        public string CReferPhone { get; set; }
        public string CRefCell { get; set; }
        public string CDoctorName { get; set; }
        public string CDoctorAddress { get; set; }
        public string CDoctorPhone { get; set; }
        public string CHospital { get; set; }
        public string CMemo { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services { get; set; }
    }
}
