//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZSRF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int serviceID { get; set; }
        public Nullable<int> clientID { get; set; }
        public string serviceType { get; set; }
        public System.DateTime serviceDate { get; set; }
        public Nullable<int> serviceCheckNum { get; set; }
        public Nullable<decimal> serviceAmnt { get; set; }
        public string memo { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> lastModified { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
